app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {

    // DB
    Route::get('/ms', function() {
        Artisan::call('migrate');
        Artisan::call('db:seed');
        return redirect('/');
    });
    Route::get('/migrate', function() {
        Artisan::call('migrate');
        return redirect('/');
    });
    Route::get('/seed', function() {
        Artisan::call('db:seed');
        return redirect('/');
    });

    // Auth
    Route::auth();

    //------------------------------------------------------------------------------------------------------------------
    // Backend

    Route::get('backend', function () {
        return redirect('backend/dashboard');
    });

    Route::group(['namespace' => 'Backend', 'prefix' => 'backend', 'middleware' => 'backend'], function() {

        // Dashboard
        Route::get('dashboard', ['as' => 'backend.dashboard', 'uses' => 'DashboardController@index']);

        // Settings
        Route::resource('settings', 'SettingsController', ['except' => ['show', 'create', 'story', 'destroy']]);

        // Static Pages
        Route::get('pages/{pages}/confirm',        ['as' => 'backend.pages.confirm', 'uses' => 'PageController@confirm']);
        Route::resource('pages', 'PageController', ['except' => 'show']);

        // Publications
        Route::group(['namespace' => 'Publications'], function() {

            // Rubrics
            Route::get('rubrics/{rubrics}/confirm',        ['as' => 'backend.rubrics.confirm',    'uses' => 'RubricController@confirm']);
            Route::post('rubrics/{rubrics}/img/upload',    ['as' => 'backend.rubrics.img.upload', 'uses' => 'RubricController@imgUpload']);
            Route::post('rubrics/{rubrics}/img/delete',    ['as' => 'backend.rubrics.img.delete', 'uses' => 'RubricController@imgDelete']);
            Route::resource('rubrics', 'RubricController', ['except' => 'show']);

            // Articles
            Route::get('articles/{articles}/confirm',        ['as' => 'backend.articles.confirm',    'uses' => 'ArticleController@confirm']);
            Route::post('articles/{articles}/img/upload',    ['as' => 'backend.articles.img.upload', 'uses' => 'ArticleController@imgUpload']);
            Route::post('articles/{articles}/img/delete',    ['as' => 'backend.articles.img.delete', 'uses' => 'ArticleController@imgDelete']);
            Route::resource('articles', 'ArticleController', ['except' => 'show']);

        });

        // Shop
        Route::group(['namespace' => 'Shop'], function() {

            // Currencies
            Route::get('currencies/{currencies}/confirm',        ['as' => 'backend.currencies.confirm', 'uses' => 'CurrencyController@confirm']);
            Route::resource('currencies', 'CurrencyController',  ['except' => 'show']);

            // Brands
            Route::get('brands/{brands}/confirm',        ['as' => 'backend.brands.confirm',    'uses' => 'BrandController@confirm']);
            Route::post('brands/{brands}/img/upload',    ['as' => 'backend.brands.img.upload', 'uses' => 'BrandController@imgUpload']);
            Route::post('brands/{brands}/img/delete',    ['as' => 'backend.brands.img.delete', 'uses' => 'BrandController@imgDelete']);
            Route::resource('brands', 'BrandController', ['except' => 'show']);

            // Categories
            Route::get('categories/{categories}/confirm',       ['as' => 'backend.categories.confirm',     'uses' => 'CategoryController@confirm']);
            Route::post('categories/{categories}/img/upload',   ['as' => 'backend.categories.img.upload',  'uses' => 'CategoryController@imgUpload']);
            Route::post('categories/{categories}/img/delete',   ['as' => 'backend.categories.img.delete',  'uses' => 'CategoryController@imgDelete']);
            Route::get('categories/{categories}/descendants',   ['as' => 'backend.categories.descendants', 'uses' => 'CategoryController@descendants']);
            Route::resource('categories', 'CategoryController', ['except' => 'show']);

            // Products
            Route::get('products/{products}/confirm',        ['as' => 'backend.products.confirm',    'uses' => 'ProductController@confirm']);
            Route::post('products/{products}/img/upload',    ['as' => 'backend.products.img.upload', 'uses' => 'ProductController@imgUpload']);
            Route::post('products/{products}/img/delete',    ['as' => 'backend.products.img.delete', 'uses' => 'ProductController@imgDelete']);
            Route::resource('products', 'ProductController', ['except' => 'show']);

        });
    });


    //------------------------------------------------------------------------------------------------------------------
    // Frontend

    Route::group(['namespace' => 'Frontend'], function() {

        // Home Page
        Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

        // Contact Page
        Route::get('contact',  ['as' => 'contact.create', 'uses' => 'ContactController@create']);
        Route::post('contact', ['as' => 'contact.store',  'uses' => 'ContactController@store']);

        // Publications
        Route::group(['namespace' => 'Publications'], function() {

            // Rubrics
            Route::get('rubrics',       ['as' => 'publications.rubrics',  'uses' => 'RubricController@index']);
            Route::get('rubric/{slug}', ['as' => 'publications.rubric',   'uses' => 'RubricController@show']);

            // Articles
            Route::get('articles',       ['as' => 'publications.articles', 'uses' => 'ArticleController@index']);
            Route::get('article/{slug}', ['as' => 'publications.article',  'uses' => 'ArticleController@show']);
        });

        // Shop
        Route::group(['namespace' => 'Shop'], function() {

            // Brands
            Route::get('brands',       ['as' => 'shop.brands', 'uses' => 'BrandController@index']);
            Route::get('brand/{slug}', ['as' => 'shop.brand',  'uses' => 'BrandController@show']);

            // Categories
            Route::get('categories',      ['as' => 'shop.categories', 'uses' => 'CategoryController@index']);
            Route::get('category/{slug}', ['as' => 'shop.category',   'uses' => 'CategoryController@show']);

            // Products
            Route::get('product/{slug}', ['as' => 'shop.product', 'uses' => 'ProductController@show']);

        });

        // Static Page
        Route::get('{slug}', ['as' => 'page', 'uses' => 'PageController@index']);

    });
});

app/Models/Shop/Brand.php
<?php

namespace App\Models\Shop;

use App\Models\Country;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    /**
     * @var mixed
     */
    private $config;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'shop_brands';

    /**
     * Guard fields from mass-assignment.
     *
     * @var array  fields to save
     */
    protected $guarded = ['id', 'created_at', 'updated_at', 'save_and_exit'];

    public function country()
    {
        return $this->belongsTo(Country::class, 'country_id');
    }


    /**
     * Rubric constructor.
     *
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->config = config('shop');
    }

    /**
     * Get the full path to image.
     */
    public function getAdminImageAttribute()
    {
        return $this->config['brand_image']['url']
        . $this->config['brand_image']['thumbnails']['admin']['sub_dir'] . $this->image;
    }

    /**
     * Get the full path to image.
     */
    public function getThImageAttribute()
    {
        return $this->config['brand_image']['url']
        . $this->config['brand_image']['thumbnails']['th']['sub_dir'] . $this->image;
    }
}

app/Http/Controllers/Backend/Shop/BrandController.php
<?php

namespace App\Http\Controllers\Backend\Shop;

use App\Models\Shop\Brand;
use App\Models\Country;
use App\Http\Requests\BrandFormRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Repositories\ImageRepository;
use Illuminate\Http\Request;

class BrandController extends Controller
{
    /**
     * BrandController constructor.
     *
     * For highlight backend menu items.
     */
    public function __construct()
    {
        // Set global var for a views
        view()->share('module', 'shop');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        session()->put('backUrl', url()->full());
        $brands = Brand::with('country')->orderBy('title')->get();

        return view('backend.shop.brand.index', ['brands' => $brands]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $countries = Country::lists('title', 'id');

        return view('backend.shop.brand.create', ['countries' => $countries]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BrandFormRequest $request
     * @param Brand $brand
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(BrandFormRequest $request, Brand $brand)
    {
        $brand = $brand->create($request->all());

        return $request->get('save_and_exit')
            ? redirect()->route('backend.brands.index')
            : redirect()->route('backend.brands.edit', [$brand]);
            //->withSuccess('Бренд создан.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Brand $brand
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Brand $brand)
    {
        $countries = Country::lists('title', 'id');

        return view('backend.shop.brand.edit', ['brand' => $brand, 'countries' => $countries]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BrandFormRequest $request
     * @param Brand $brand
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(BrandFormRequest $request, Brand $brand)
    {
        $brand->update($request->all());

        return $request->get('save_and_exit')
            ? redirect()->route('backend.brands.index')
            : redirect()->route('backend.brands.edit', [$brand]);
            //->withSuccess('Изменения сохранены.');
    }

    /**
     * @param Request $request
     * @param Brand $brand
     * @param ImageRepository $imageRepository
     * @return \Illuminate\Http\JsonResponse
     */
    public function imgUpload(Request $request, Brand $brand, ImageRepository $imageRepository)
    {
        if ($request->ajax()) {
            $imageRepository->init('shop.brand_image', $brand, $request);

            $validator = $imageRepository->validator();
            if ($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => $validator->messages()->first(),
                ], 400);
            }

            $imageRepository->uploadImage();

            return response()->json([
                'success' => true,
                'image'   => $brand->admin_image,
            ], 200);
        } else {
            return response('Bad Request', 400);
        }
    }

    /**
     * @param Request $request
     * @param Brand $brand
     * @param ImageRepository $imageRepository
     * @return \Illuminate\Http\JsonResponse
     */
    public function imgDelete(Request $request, Brand $brand, ImageRepository $imageRepository)
    {
        if ($request->ajax()) {
            $imageRepository->init('shop.brand_image', $brand, $request);
            $imageRepository->deleteImage();

            return response()->json([
                'success' => true,
            ], 200);
        } else {
            return response('Bad Request', 400);
        }
    }

    /**
     * Show the form for confirmation delete resource.
     *
     * @param Brand $brand
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function confirm(Brand $brand)
    {
        return view('backend.shop.brand.confirm', ['brand' => $brand]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param ImageRepository $imageRepository
     * @param Brand $brand
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Brand $brand, ImageRepository $imageRepository)
    {
        $brand->delete();

        $imageRepository->init('shop.brand_image', $brand);
        $imageRepository->deleteFiles();

        return redirect()
            ->route('backend.brands.index')
            ->withSuccess('Бренд удален.');
    }
}

app/Http/Controllers/Backend/Shop/CurrencyController.php
<?php

namespace App\Http\Controllers\Backend\Shop;

use App\Models\Shop\Currency;
use App\Http\Requests\CurrencyFormRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class CurrencyController extends Controller
{
    /**
     * CurrencyController constructor.
     *
     * For highlight backend menu items.
     */
    public function __construct()
    {
        // Set global var for a views
        view()->share('module', 'settings');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        session()->put('backUrl', url()->full());
        $currencies = Currency::orderBy('is_main', 'desc')->get();

        return view('backend.shop.currency.index', ['currencies' => $currencies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.shop.currency.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  CurrencyFormRequest $request
     * @param  Currency $currency
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(CurrencyFormRequest $request, Currency $currency)
    {
        $currency_main = Currency::where('is_main', 1)->first();
        $currency = $currency->create($request->all());
        $currency->saveIsMain($currency_main);

        return $request->get('save_and_exit')
            ? redirect()->route('backend.currencies.index')
            : redirect()->route('backend.currencies.edit', [$currency]);
            //->withSuccess('Новая валюта создана.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Currency $currency
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Currency $currency)
    {
        return view('backend.shop.currency.edit', ['currency' => $currency]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CurrencyFormRequest $request
     * @param  Currency $currency
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(CurrencyFormRequest $request, Currency $currency)
    {
        $currency_main = Currency::where('is_main', 1)->first();
        $currency->update($request->all());
        $currency->saveIsMain($currency_main);

        return $request->get('save_and_exit')
            ? redirect()->route('backend.currencies.index')
            : redirect()->route('backend.currencies.edit', [$currency]);
            //->withSuccess('Изменения сохранены.');
    }

    /**
     * Show the form for confirmation delete resource.
     *
     * @param Currency $currency
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function confirm(Currency $currency)
    {
        return view('backend.shop.currency.confirm', ['currency' => $currency]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Currency $currency
     * @return \Illuminate\Http\Response
     */
    public function destroy(Currency $currency)
    {
        if ($currency->is_main) {
            return redirect()
                ->route('backend.currencies.confirm', ['currency' => $currency])
                ->withErrors('Вы не можете удалить основную валюту.');
        }

        $currency->delete();

        return redirect()
            ->route('backend.currencies.index')
            ->withSuccess('Валюта удалена.');
    }
}

app/Http/Controllers/Frontend/Shop/BrandController.php
<?php

namespace App\Http\Controllers\Frontend\Shop;

use App\Models\Shop\Brand;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class BrandController extends Controller
{
    /**
     * Display Brands
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $brands = Brand::where('id', '>', 1)->get();

        $breadcrumbs[] = ['label' => 'Бренды'];

        return view('frontend.shop.brand.index', [
            'breadcrumbs' => $breadcrumbs,
            'brands'      => $brands,
        ]);
    }


    public function show($slug)
    {
        $brand = Brand::whereSlug($slug)->where('id', '>', 1)->firstOrFail();

        $breadcrumbs[] = ['label' => 'Бренды', 'url' => route('shop.brands')];
        $breadcrumbs[] = ['label' => $brand->title];

        return view('frontend.shop.brand.show', [
            'breadcrumbs' => $breadcrumbs,
            'brand'       => $brand,
        ]);
    }
}

resources/views/backend/shop/brand/_form.blade.php
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#page" aria-controls="page" role="tab" data-toggle="tab">Бренд</a>
    </li>
    <li role="presentation">
        <a href="#seo" aria-controls="seo" role="tab" data-toggle="tab">SEO</a>
    </li>
</ul>
<br>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="page">

        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
            {!! Form::label('title', 'Название', ['class' => 'col-md-2 control-label']) !!}
            <div class="col-md-10">
                {!! Form::text('title', null, ['class' => 'form-control']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('country_id', 'Страна', ['class' => 'col-md-2 control-label']) !!}
            <div class="col-md-10">
                {!! Form::select('country_id', $countries, null, ['id' => 'country_id', 'class' => 'form-control']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('preview', 'Краткое описание', ['class' => 'col-md-2 control-label']) !!}
            <div class="col-md-10">
                {!! Form::textarea('preview', null, ['class' => 'form-control']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('content', 'Полное описание', ['class' => 'col-md-2 control-label']) !!}
            <div class="col-md-10">
                {!! Form::textarea('content', null, ['class' => 'form-control']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('image', 'Изображение', ['class' => 'col-md-2 control-label']) !!}
            <div class="col-md-10">
                @if (isset($brand))
                    @include('backend.form_image', ['object' => $brand])
                @else
                    <div class="alert alert-warning" role="alert">
                        Для загрузки изображения сохраните бренд.
                    </div>
                @endif
            </div>
        </div>

    </div>
    <div role="tabpanel" class="tab-pane fade" id="seo">

        @include('backend.form_seo')

    </div>
</div>

@section('scripts')
    <script src="/vendor/midium/laravel-ckeditor/ckeditor.js"></script>
    <script>
        $(function () {
            CKEDITOR.replace('preview', { customConfig: '/public/assets/backend/js/ck_preview.js' });
            CKEDITOR.replace('content', { customConfig: '/public/assets/backend/js/ck_content.js' });
            $('#country_id').select2();

            <?php if (isset($brand)): ?>
                var objectID = '{{ $brand->id }}';
                APP.imageUpload(objectID, '{{ route('backend.brands.img.upload', $brand->id) }}');
                $('#deleteBtn' + objectID).click(function(e) {
                    e.preventDefault();
                    APP.imageDelete(objectID, '{{ route('backend.brands.img.delete', $brand->id) }}');
                });
            <?php endif ?>
        });
    </script>
@stop

resources/views/backend/shop/brand/confirm.blade.php
@extends('backend.layouts.default')

@section('title', 'Удалить бренд' . $brand->title)

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Каталог товаров<small><i class="fa fa-angle-right fa-fw"></i>Удалить бренд</small>
            </h1>
        </div>
    </div>

    {!! Form::open([
        'method' => 'DELETE',
        'route'  => ['backend.brands.destroy', $brand->id]
    ]) !!}

    <div class="alert alert-danger">
        <p><strong>Внимание!</strong> Вы действительно хотите удалить этот бренд?</p>
        <p><i class="fa fa-file-o fa-fw"></i> {{ $brand->title }}</p>
    </div>

    {!! Form::submit('Да, удалить этот бренд!', ['class' => 'btn btn-danger']) !!}

    <a href="{{ route('backend.articles.index') }}" class="btn btn-success">
        <strong>Нет, вернуться назад!</strong>
    </a>

    {!! Form::close() !!}

@stop

resources/views/backend/shop/brand/create.blade.php
@extends('backend.layouts.default')

@section('title', 'Добавить бренд')

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Каталог товаров<small><i class="fa fa-angle-right fa-fw"></i>Добавить бренд</small>
            </h1>
        </div>
    </div>

    {!! Form::open([
        'route'  => 'backend.brands.store',
        'class'  => 'form-horizontal'
    ]) !!}

    @include ('backend.shop.brand._form')
    @include ('backend.form_buttons')

    {!! Form::close() !!}

@stop

resources/views/backend/shop/brand/edit.blade.php
@extends('backend.layouts.default')

@section('title', 'Редактировать бренд')

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Каталог товаров<small><i class="fa fa-angle-right fa-fw"></i>Редактировать бренд</small>
            </h1>
        </div>
    </div>

    {!! Form::model($brand, [
        'method' => 'PATCH',
        'route'  => ['backend.brands.update', $brand->id],
        'class'  => 'form-horizontal'
    ]) !!}

    @include ('backend.shop.brand._form')
    @include ('backend.form_buttons')

    {!! Form::close() !!}

@stop

resources/views/backend/shop/brand/index.blade.php
@extends('backend.layouts.default')

@section('title', 'Управление брендами')

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Каталог товаров<small><i class="fa fa-angle-right fa-fw"></i>Управление брендами</small>
            </h1>
            <div class="btn-group">
                <a href="{{ route('backend.brands.create') }}" class="btn btn-success btn-sm">
                    <i class="fa fa-plus-circle fa-fw"></i> Добавить бренд
                </a>
            </div><hr>
        </div>
    </div>

    @if($brands->count())
        <table class="table table-striped table-hover">

            <thead>
            <tr>
                <th>Изображение</th>
                <th style="width: 75%">Бренд</th>
                <th>Действия</th>
            </tr>
            </thead>

            <tbody>
            @foreach($brands as $brand)
                <tr>
                    <td>
                        @if($brand->image)
                            <img src="{{ $brand->admin_image }}" alt="" width="52">
                        @endif
                    </td>

                    <td>
                        <a href="{{ route('backend.brands.edit', $brand->id) }}">
                            {{ $brand->title }}
                        </a><br>
                        <small>
                            Страна:
                            @if($brand->country->id == 1)
                                <span class="text-danger">{{ $brand->country->title }}</span>
                            @else
                                {{ $brand->country->title }}
                            @endif
                        </small>
                    </td>

                    <td class="icon_actions">
                        <a href="{{ route('backend.brands.edit', $brand->id ) }}" >
                            <i class="fa fa-pencil fa-lg fa-fw"></i></a>

                        {{--<a href="{{ route('brand', $brand->slug) }}" target="_blank">--}}
                            {{--<i class="fa fa-eye fa-lg fa-fw"></i></a>--}}

                        <a href="{{ route('backend.brands.confirm', $brand->id) }}">
                            <i class="fa fa-remove fa-lg fa-fw text-danger"></i></a>
                    </td>
                </tr>
            @endforeach
            </tbody>

        </table>
    @else
        <p>Список брендов пуст!</p>
    @endif

@stop