app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {

    // DB
    Route::get('/ms', function() {
        Artisan::call('migrate');
        Artisan::call('db:seed');
        return redirect('/');
    });
    Route::get('/migrate', function() {
        Artisan::call('migrate');
        return redirect('/');
    });
    Route::get('/seed', function() {
        Artisan::call('db:seed');
        return redirect('/');
    });

    // Auth
    Route::auth();

    //------------------------------------------------------------------------------------------------------------------
    // Backend

    Route::get('backend', function () {
        return redirect('backend/dashboard');
    });

    Route::group(['namespace' => 'Backend', 'prefix' => 'backend', 'middleware' => 'backend'], function() {

        // Dashboard
        Route::get('dashboard', ['as' => 'backend.dashboard', 'uses' => 'DashboardController@index']);

        // Settings
        Route::resource('settings', 'SettingsController', ['except' => ['show', 'create', 'story', 'destroy']]);

        // Static Pages
        Route::get('pages/{pages}/confirm',        ['as' => 'backend.pages.confirm', 'uses' => 'PageController@confirm']);
        Route::resource('pages', 'PageController', ['except' => 'show']);

        // Publications
        Route::group(['namespace' => 'Publications'], function() {

            // Rubrics
            Route::get('rubrics/{rubrics}/confirm',        ['as' => 'backend.rubrics.confirm',    'uses' => 'RubricController@confirm']);
            Route::post('rubrics/{rubrics}/img/upload',    ['as' => 'backend.rubrics.img.upload', 'uses' => 'RubricController@imgUpload']);
            Route::post('rubrics/{rubrics}/img/delete',    ['as' => 'backend.rubrics.img.delete', 'uses' => 'RubricController@imgDelete']);
            Route::resource('rubrics', 'RubricController', ['except' => 'show']);

            // Articles
            Route::get('articles/{articles}/confirm',        ['as' => 'backend.articles.confirm',    'uses' => 'ArticleController@confirm']);
            Route::post('articles/{articles}/img/upload',    ['as' => 'backend.articles.img.upload', 'uses' => 'ArticleController@imgUpload']);
            Route::post('articles/{articles}/img/delete',    ['as' => 'backend.articles.img.delete', 'uses' => 'ArticleController@imgDelete']);
            Route::resource('articles', 'ArticleController', ['except' => 'show']);

        });

        // Shop
        Route::group(['namespace' => 'Shop'], function() {

            // Currencies
            Route::get('currencies/{currencies}/confirm',        ['as' => 'backend.currencies.confirm', 'uses' => 'CurrencyController@confirm']);
            Route::resource('currencies', 'CurrencyController',  ['except' => 'show']);

            // Brands
            Route::get('brands/{brands}/confirm',        ['as' => 'backend.brands.confirm',    'uses' => 'BrandController@confirm']);
            Route::post('brands/{brands}/img/upload',    ['as' => 'backend.brands.img.upload', 'uses' => 'BrandController@imgUpload']);
            Route::post('brands/{brands}/img/delete',    ['as' => 'backend.brands.img.delete', 'uses' => 'BrandController@imgDelete']);
            Route::resource('brands', 'BrandController', ['except' => 'show']);

            // Categories
            Route::get('categories/{categories}/confirm',       ['as' => 'backend.categories.confirm',     'uses' => 'CategoryController@confirm']);
            Route::post('categories/{categories}/img/upload',   ['as' => 'backend.categories.img.upload',  'uses' => 'CategoryController@imgUpload']);
            Route::post('categories/{categories}/img/delete',   ['as' => 'backend.categories.img.delete',  'uses' => 'CategoryController@imgDelete']);
            Route::get('categories/{categories}/descendants',   ['as' => 'backend.categories.descendants', 'uses' => 'CategoryController@descendants']);
            Route::resource('categories', 'CategoryController', ['except' => 'show']);

            // Products
            Route::get('products/{products}/confirm',        ['as' => 'backend.products.confirm',    'uses' => 'ProductController@confirm']);
            Route::post('products/{products}/img/upload',    ['as' => 'backend.products.img.upload', 'uses' => 'ProductController@imgUpload']);
            Route::post('products/{products}/img/delete',    ['as' => 'backend.products.img.delete', 'uses' => 'ProductController@imgDelete']);
            Route::resource('products', 'ProductController', ['except' => 'show']);

        });
    });


    //------------------------------------------------------------------------------------------------------------------
    // Frontend

    Route::group(['namespace' => 'Frontend'], function() {

        // Home Page
        Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

        // Contact Page
        Route::get('contact',  ['as' => 'contact.create', 'uses' => 'ContactController@create']);
        Route::post('contact', ['as' => 'contact.store',  'uses' => 'ContactController@store']);

        // Publications
        Route::group(['namespace' => 'Publications'], function() {

            // Rubrics
            Route::get('rubrics',       ['as' => 'publications.rubrics',  'uses' => 'RubricController@index']);
            Route::get('rubric/{slug}', ['as' => 'publications.rubric',   'uses' => 'RubricController@show']);

            // Articles
            Route::get('articles',       ['as' => 'publications.articles', 'uses' => 'ArticleController@index']);
            Route::get('article/{slug}', ['as' => 'publications.article',  'uses' => 'ArticleController@show']);
        });

        // Shop
        Route::group(['namespace' => 'Shop'], function() {

            // Brands
            Route::get('brands',       ['as' => 'shop.brands', 'uses' => 'BrandController@index']);
            Route::get('brand/{slug}', ['as' => 'shop.brand',  'uses' => 'BrandController@show']);

            // Categories
            Route::get('categories',      ['as' => 'shop.categories', 'uses' => 'CategoryController@index']);
            Route::get('category/{slug}', ['as' => 'shop.category',   'uses' => 'CategoryController@show']);

            // Products
            Route::get('product/{slug}', ['as' => 'shop.product', 'uses' => 'ProductController@show']);

        });

        // Static Page
        Route::get('{slug}', ['as' => 'page', 'uses' => 'PageController@index']);

    });
});

app/Models/Shop/Brand.php
<?php

namespace App\Models\Shop;

use App\Models\Country;
use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    /**
     * @var mixed
     */
    private $config;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'shop_brands';

    /**
     * Guard fields from mass-assignment.
     *
     * @var array  fields to save
     */
    protected $guarded = ['id', 'created_at', 'updated_at', 'save_and_exit'];

    public function country()
    {
        return $this->belongsTo(Country::class, 'country_id');
    }


    /**
     * Rubric constructor.
     *
     * @param array $attributes
     */
    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->config = config('shop');
    }

    /**
     * Get the full path to image.
     */
    public function getAdminImageAttribute()
    {
        return $this->config['brand_image']['url']
        . $this->config['brand_image']['thumbnails']['admin']['sub_dir'] . $this->image;
    }

    /**
     * Get the full path to image.
     */
    public function getThImageAttribute()
    {
        return $this->config['brand_image']['url']
        . $this->config['brand_image']['thumbnails']['th']['sub_dir'] . $this->image;
    }
}

resources/views/widgets/brands_home.blade.php
<h2 class="page-header">
    Бренды
    <small>
        <i class="fa fa-angle-right fa-fw"></i>
        <a href="{{ route('shop.brands') }}">Все бренды</a>
    </small>
</h2>

<div class="row">
    @foreach($brands as $brand)

        <div class="col-xs-3 col-sm-2 col-md-2 col-lg-1">
            <a href="{{ route('shop.brand', ['slug' => $brand->slug]) }}" class="thumbnail">
                <img src="{{ $brand->th_image }}" alt="{{ $brand->title }}">
            </a>
        </div>

    @endforeach
</div>

resources/views/widgets/breadcrumbs.blade.php
<ol class="breadcrumb">
    <li>
        <a href="/"><i class="fa fa-home"></i></a>
    </li>
    @foreach($breadcrumbs as $breadcrumb)
        @if(isset($breadcrumb['url']))
            <li><a href="{{ $breadcrumb['url'] }}">{{ $breadcrumb['label'] }}</a></li>
        @else
            <li class="active">{{ $breadcrumb['label'] }}</li>
        @endif
    @endforeach
</ol>

resources/views/widgets/nav_categories.blade.php
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">{{ $title  }}</h3>
    </div>
    <div class="panel-body">
        @foreach($categories as $category)
            @if($category['depth'] == 2)
                <i class="fa fa-fw fa-angle-right"></i>
            @endif
            <a href="{{ route('shop.category', ['slug' => $category['slug']]) }}">
                {{ $category['title'] }}</a>
            <br>
        @endforeach
    </div>
</div>

resources/views/widgets/nav_header.blade.php
@if(count($pages))
    @foreach($pages as $page)
        <div class="nowrap">
            <i class="fa {{ $page->icon }} fa-fw"></i>
            <a href="{{ route('page', ['slug' => $page->slug]) }}">{{ $page->title }}</a>
        </div>
    @endforeach
    <br>
@endif

@if(count($pages))
    @foreach($rubrics as $rubric)
        <div class="nowrap">
            <i class="fa {{ $rubric->icon }} fa-fw"></i>
            <a href="{{ route('publications.rubric', $rubric->slug) }}">{{ $rubric->title }}</a>
        </div>
    @endforeach
    <br>
@endif

<div class="nowrap">
    <i class="fa fa-folder-o fa-fw"></i>
    <a href="{{ route('shop.categories') }}">Категории</a>
</div>

<div class="nowrap">
    <i class="fa fa-apple fa-fw"></i>
    <a href="{{ route('shop.brands') }}">Бренды</a>
</div>

<div class="nowrap">
    <i class="fa fa-envelope-o fa-fw"></i>
    <a href="{{ route('contact.create') }}">Контакты</a>
</div>

resources/views/widgets/nav_header_categories.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                @foreach($categories as $category)
                    <li>
                        <a href="{{ route('shop.category', ['slug' => $category->slug]) }}">
                            {{ $category->title }}
                        </a>
                    </li>
                @endforeach
            </ul>
        </div><!--/.nav-collapse -->
    </div><!--/.container-fluid -->
</nav>

resources/views/widgets/nav_pages.blade.php
<div class="list-group">
    <a href="{{ route('shop.categories') }}" class="list-group-item">
        <i class="fa fa-folder-o fa-fw"></i> Категории товаров
    </a>
    <a href="{{ route('shop.brands') }}" class="list-group-item">
        <i class="fa fa-apple fa-fw"></i> Бренды
    </a>
    @foreach($rubrics as $rubric)
        <a href="{{ route('publications.rubric', $rubric->slug) }}" class="list-group-item">
            <i class="fa {{ $rubric->icon }} fa-fw"></i> {{ $rubric->title }}
        </a>
    @endforeach
    @foreach($pages as $page)
        <a href="{{ route('page', ['slug' => $page->slug]) }}" class="list-group-item">
            <i class="fa {{ $page->icon }} fa-fw"></i> {{ $page->title }}
        </a>
    @endforeach
    <a href="{{ route('contact.create') }}" class="list-group-item">
        <i class="fa fa-envelope-o fa-fw"></i> Контакты
    </a>
</div>

resources/views/widgets/product_on_home_page.blade.php
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#popular_products" data-toggle="tab">Хиты</a>
    </li>
    <li>
        <a href="#new_products" data-toggle="tab">Новинки</a>
    </li>
    <li>
        <a href="#action_products" data-toggle="tab">Спецпредложения</a>
    </li>
</ul>
<br>

<div class="tab-content">
    <div class="tab-pane fade in active" id="popular_products">
        <div class="row">
            @foreach($hits as $hit)
                <div class="col-sm-3 col-md-3 col-lg-2">
                    <div class="thumbnail">
                        <img src="{{ $hit->th_image }}" alt="{{ $hit->title }}">
                        <div class="caption">
                            <h3><a href="{{ route('shop.product', $hit->slug) }}">{{ $hit->title }}</a></h3>
                            <p><strong>Цена:</strong> <span class="label label-primary">{!! $hit->priceOnPageUAN !!}</span></p>
                            <a href="#" class="btn-add-to-cart btn btn-success btn-xs">
                                <i class="fa fa-plus fa-fw"></i> В корзину
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="tab-pane fade" id="new_products">
        <div class="row">
            @foreach($hots as $hot)
                <div class="col-sm-3 col-md-3 col-lg-2">
                    <div class="thumbnail">
                        <img src="{{ $hot->th_image }}" alt="{{ $hot->title }}">
                        <div class="caption">
                            <h3><a href="{{ route('shop.product', $hot->slug) }}">{{ $hot->title }}</a></h3>
                            <p><strong>Цена:</strong> <span class="label label-primary">{!! $hot->priceOnPageUAN !!}</span></p>
                            <a href="#" class="btn-add-to-cart btn btn-success btn-xs">
                                <i class="fa fa-plus fa-fw"></i> В корзину
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="tab-pane fade" id="action_products">
        <div class="row">
            @foreach($actions as $action)
                <div class="col-sm-3 col-md-3 col-lg-2">
                    <div class="thumbnail">
                        <img src="{{ $action->th_image }}" alt="{{ $action->title }}">
                        <div class="caption">
                            <h3><a href="{{ route('shop.product', $action->slug) }}">{{ $action->title }}</a></h3>
                            <p><strong>Цена:</strong> <span class="label label-primary">{!! $action->priceOnPageUAN !!}</span></p>
                            <a href="#" class="btn-add-to-cart btn btn-success btn-xs">
                                <i class="fa fa-plus fa-fw"></i> В корзину
                            </a>
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
    </div>
</div>

resources/views/widgets/recent_publications.blade.php
<h2 class="page-header">
    Последние публикации
    <small>
        <i class="fa fa-angle-right fa-fw"></i>
        <a href="{{ route('publications.articles') }}">Все публикации</a>
    </small>
</h2>

@foreach($articles as $article)
    <div class="row">
        <div class="col-sm-3">
            @if($article->image)
                <a href="{{ route('publications.article', $article->slug)  }}" class="thumbnail">
                    <img src="{{ $article->th_image }}" alt="{{ $article->title }}">
                </a>
            @endif
        </div>
        <div class="col-sm-9">
            <h3>
                {!! Html::linkRoute('publications.article', $article->title, $article->slug) !!}
            </h3>
            {!! $article->preview !!}
            <p>
                <i class="fa fa-folder-o fa-fw"></i>
                {!! Html::linkRoute('publications.rubric', $article->rubric->title, $article->rubric->slug) !!}
                <i class="fa fa-calendar fa-fw"></i>
                <small>{{ $article->published_at }}</small>
            </p>
        </div>
    </div>
@endforeach