app/Http/routes.php
<?php

Route::group(['middleware' => ['web']], function () {

    // DB
    Route::get('/ms', function() {
        Artisan::call('migrate');
        Artisan::call('db:seed');
        return redirect('/');
    });
    Route::get('/migrate', function() {
        Artisan::call('migrate');
        return redirect('/');
    });
    Route::get('/seed', function() {
        Artisan::call('db:seed');
        return redirect('/');
    });

    // Auth
    Route::auth();

    //------------------------------------------------------------------------------------------------------------------
    // Backend

    Route::get('backend', function () {
        return redirect('backend/dashboard');
    });

    Route::group(['namespace' => 'Backend', 'prefix' => 'backend', 'middleware' => 'backend'], function() {

        // Dashboard
        Route::get('dashboard', ['as' => 'backend.dashboard', 'uses' => 'DashboardController@index']);

        // Settings
        Route::resource('settings', 'SettingsController', ['except' => ['show', 'create', 'story', 'destroy']]);

        // Static Pages
        Route::get('pages/{pages}/confirm',        ['as' => 'backend.pages.confirm', 'uses' => 'PageController@confirm']);
        Route::resource('pages', 'PageController', ['except' => 'show']);

        // Publications
        Route::group(['namespace' => 'Publications'], function() {

            // Rubrics
            Route::get('rubrics/{rubrics}/confirm',        ['as' => 'backend.rubrics.confirm',    'uses' => 'RubricController@confirm']);
            Route::post('rubrics/{rubrics}/img/upload',    ['as' => 'backend.rubrics.img.upload', 'uses' => 'RubricController@imgUpload']);
            Route::post('rubrics/{rubrics}/img/delete',    ['as' => 'backend.rubrics.img.delete', 'uses' => 'RubricController@imgDelete']);
            Route::resource('rubrics', 'RubricController', ['except' => 'show']);

            // Articles
            Route::get('articles/{articles}/confirm',        ['as' => 'backend.articles.confirm',    'uses' => 'ArticleController@confirm']);
            Route::post('articles/{articles}/img/upload',    ['as' => 'backend.articles.img.upload', 'uses' => 'ArticleController@imgUpload']);
            Route::post('articles/{articles}/img/delete',    ['as' => 'backend.articles.img.delete', 'uses' => 'ArticleController@imgDelete']);
            Route::resource('articles', 'ArticleController', ['except' => 'show']);

        });

        // Shop
        Route::group(['namespace' => 'Shop'], function() {

            // Currencies
            Route::get('currencies/{currencies}/confirm',        ['as' => 'backend.currencies.confirm', 'uses' => 'CurrencyController@confirm']);
            Route::resource('currencies', 'CurrencyController',  ['except' => 'show']);

            // Brands
            Route::get('brands/{brands}/confirm',        ['as' => 'backend.brands.confirm',    'uses' => 'BrandController@confirm']);
            Route::post('brands/{brands}/img/upload',    ['as' => 'backend.brands.img.upload', 'uses' => 'BrandController@imgUpload']);
            Route::post('brands/{brands}/img/delete',    ['as' => 'backend.brands.img.delete', 'uses' => 'BrandController@imgDelete']);
            Route::resource('brands', 'BrandController', ['except' => 'show']);

            // Categories
            Route::get('categories/{categories}/confirm',       ['as' => 'backend.categories.confirm',     'uses' => 'CategoryController@confirm']);
            Route::post('categories/{categories}/img/upload',   ['as' => 'backend.categories.img.upload',  'uses' => 'CategoryController@imgUpload']);
            Route::post('categories/{categories}/img/delete',   ['as' => 'backend.categories.img.delete',  'uses' => 'CategoryController@imgDelete']);
            Route::get('categories/{categories}/descendants',   ['as' => 'backend.categories.descendants', 'uses' => 'CategoryController@descendants']);
            Route::resource('categories', 'CategoryController', ['except' => 'show']);

            // Products
            Route::get('products/{products}/confirm',        ['as' => 'backend.products.confirm',    'uses' => 'ProductController@confirm']);
            Route::post('products/{products}/img/upload',    ['as' => 'backend.products.img.upload', 'uses' => 'ProductController@imgUpload']);
            Route::post('products/{products}/img/delete',    ['as' => 'backend.products.img.delete', 'uses' => 'ProductController@imgDelete']);
            Route::resource('products', 'ProductController', ['except' => 'show']);

        });
    });


    //------------------------------------------------------------------------------------------------------------------
    // Frontend

    Route::group(['namespace' => 'Frontend'], function() {

        // Home Page
        Route::get('/', ['as' => 'home', 'uses' => 'HomeController@index']);

        // Contact Page
        Route::get('contact',  ['as' => 'contact.create', 'uses' => 'ContactController@create']);
        Route::post('contact', ['as' => 'contact.store',  'uses' => 'ContactController@store']);

        // Publications
        Route::group(['namespace' => 'Publications'], function() {

            // Rubrics
            Route::get('rubrics',       ['as' => 'publications.rubrics',  'uses' => 'RubricController@index']);
            Route::get('rubric/{slug}', ['as' => 'publications.rubric',   'uses' => 'RubricController@show']);

            // Articles
            Route::get('articles',       ['as' => 'publications.articles', 'uses' => 'ArticleController@index']);
            Route::get('article/{slug}', ['as' => 'publications.article',  'uses' => 'ArticleController@show']);
        });

        // Shop
        Route::group(['namespace' => 'Shop'], function() {

            // Brands
            Route::get('brands',       ['as' => 'shop.brands', 'uses' => 'BrandController@index']);
            Route::get('brand/{slug}', ['as' => 'shop.brand',  'uses' => 'BrandController@show']);

            // Categories
            Route::get('categories',      ['as' => 'shop.categories', 'uses' => 'CategoryController@index']);
            Route::get('category/{slug}', ['as' => 'shop.category',   'uses' => 'CategoryController@show']);

            // Products
            Route::get('product/{slug}', ['as' => 'shop.product', 'uses' => 'ProductController@show']);

        });

        // Static Page
        Route::get('{slug}', ['as' => 'page', 'uses' => 'PageController@index']);

    });
});

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    /**
     * DashboardController constructor.
     *
     * For highlight backend menu items.
     */
    public function __construct()
    {
        // Set global var for a views
        view()->share('module', 'dashboard');
    }

    /**
     * Display a Dashboard page.
     */
    public function index()
    {
        return view('backend.dashboard.index');
    }
}

app/Http/Controllers/Backend/PageController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Page;
use App\Http\Requests\PageFormRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class PageController extends Controller
{
    /**
     * PageController constructor.
     *
     * For highlight backend menu items.
     */
    public function __construct()
    {
        // Set global var for a views
        view()->share('module', 'pages');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        session()->put('backUrl', url()->full());
        $pages = Page::all();

        return view('backend.page.index', ['pages' => $pages]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.page.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PageFormRequest $request
     * @param Page $page
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(PageFormRequest $request, Page $page)
    {
        $page = $page->create($request->all());

        return $request->get('save_and_exit')
            ? redirect()->route('backend.pages.index')
            : redirect()->route('backend.pages.edit', [$page]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Page $page
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Page $page)
    {
        return view('backend.page.edit', ['page' => $page]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PageFormRequest $request
     * @param Page $page
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(PageFormRequest $request, Page $page)
    {
        $page->update($request->all());

        return $request->get('save_and_exit')
            ? redirect()->route('backend.pages.index')
            : redirect()->route('backend.pages.edit', [$page]);
    }

    /**
     * Show the form for confirmation delete resource.
     *
     * @param Page $page
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function confirm(Page $page)
    {
        return view('backend.page.confirm', ['page' => $page]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Page $page
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function destroy(Page $page)
    {
        $page->delete();

        return redirect()
            ->route('backend.pages.index')
            ->withSuccess('Page deleted.');
    }
}

app/Http/Controllers/Backend/Publications/ArticleController.php
<?php

namespace App\Http\Controllers\Backend\Publications;

use App\Models\Publications\Rubric;
use App\Models\Publications\Article;
use App\Http\Requests\ArticleFormRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Repositories\ImageRepository;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    /**
     * ArticleController constructor.
     *
     * For highlight backend menu items.
     */
    public function __construct()
    {
        // Set global var for a views
        view()->share('module', 'publications');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        session()->put('backUrl', url()->full());

        $articles = Article::with('rubric')
            ->latest('created_at')
            ->paginate(12);

        return view('backend.publications.article.index', ['articles' => $articles]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $rubrics = Rubric::lists('title', 'id');

        return view('backend.publications.article.create', ['rubrics' => $rubrics]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ArticleFormRequest $request
     * @param Article $article
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(ArticleFormRequest $request, Article $article)
    {
        $article = $article->create($request->all());

        return $request->get('save_and_exit')
            ? redirect()->route('backend.articles.index')
            : redirect()->route('backend.articles.edit', [$article]);
            //->withSuccess('New Article Created.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        $rubrics = Rubric::lists('title', 'id');

        return view('backend.publications.article.edit', [
            'rubrics' => $rubrics,
            'article' => $article,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  ArticleFormRequest $request
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleFormRequest $request, Article $article)
    {
        $article->update($request->all());

        return $request->get('save_and_exit')
            ? redirect()->route('backend.articles.index')
            : redirect()->route('backend.articles.edit', [$article]);
            //->withSuccess('Article saved.');
    }

    /**
     * @param Request $request
     * @param Article $article
     * @param ImageRepository $imageRepository
     * @return \Illuminate\Http\JsonResponse
     */
    public function imgUpload(Request $request, Article $article, ImageRepository $imageRepository)
    {
        if ($request->ajax()) {
            $imageRepository->init('publications.article_image', $article, $request);

            $validator = $imageRepository->validator();
            if ($validator->fails()) {
                return response()->json([
                    'success' => false,
                    'message' => $validator->messages()->first(),
                ], 400);
            }

            $imageRepository->uploadImage();

            return response()->json([
                'success' => true,
                'image'   => $article->admin_image,
            ], 200);
        } else {
            return response('Bad Request', 400);
        }
    }

    /**
     * @param Request $request
     * @param Article $article
     * @param ImageRepository $imageRepository
     * @return \Illuminate\Http\JsonResponse
     */
    public function imgDelete(Request $request, Article $article, ImageRepository $imageRepository)
    {
        if ($request->ajax()) {
            $imageRepository->init('publications.article_image', $article, $request);
            $imageRepository->deleteImage();

            return response()->json([
                'success' => true,
            ], 200);
        } else {
            return response('Bad Request', 400);
        }
    }

    /**
     * Show the form for confirmation delete resource.
     *
     * @param Article $article
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function confirm(Article $article)
    {
        return view('backend.publications.article.confirm', ['article' => $article]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Article $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article, ImageRepository $imageRepository)
    {
        $article->delete();

        $imageRepository->init('publications.article_image', $article);
        $imageRepository->deleteFiles();

        return redirect()
            ->route('backend.articles.index')
            ->withSuccess('Article deleted.');
    }
}

app/Http/Controllers/Backend/SettingsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Settings;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class SettingsController extends Controller
{
    /**
     * SettingsController constructor.
     *
     * For highlight backend menu items.
     */
    public function __construct()
    {
        // Set global var for a views
        view()->share('module', 'settings');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $settings = Settings::all();

        return view('backend.settings.index', ['settings' => $settings]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Settings $setting
     * @return \Illuminate\Http\Response
     */
    public function edit(Settings $setting)
    {
        return view('backend.settings.edit', ['setting' => $setting]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Settings $setting
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Settings $setting)
    {
        $setting->update($request->all());

        return redirect()
            ->route('backend.settings.index')
            ->withSuccess('Parameter saved.');
    }
}

resources/views/backend/page/_form.blade.php
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active">
        <a href="#page" aria-controls="page" role="tab" data-toggle="tab">Страница</a>
    </li>
    <li role="presentation">
        <a href="#seo" aria-controls="seo" role="tab" data-toggle="tab">SEO</a>
    </li>
</ul>
<br>

<div class="tab-content">
    <div role="tabpanel" class="tab-pane fade in active" id="page">

        <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
            {!! Form::label('title', 'Заголовок страницы', ['class' => 'col-md-2 control-label']) !!}
            <div class="col-md-10">
                {!! Form::text('title', null, ['class' => 'form-control']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('content', 'Текст страницы', ['class' => 'col-md-2 control-label']) !!}
            <div class="col-md-10">
                {!! Form::textarea('content', null, ['class' => 'form-control']) !!}
            </div>
        </div>

        <div class="form-group">
            {!! Form::label('icon', 'Название иконки', ['class' => 'col-md-2 control-label']) !!}
            <div class="col-sm-10">
                {!! Form::text('icon', null, ['class' => 'form-control', 'placeholder' => 'fa-info']) !!}
                <span class="help-block">
                    <a href="http://fortawesome.github.io/Font-Awesome/icons" target="_blank">
                        Набор допустимых иконок <small><i class="fa fa-external-link fa-fw"></i></small>
                    </a>
                </span>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10 col-md-offset-2">
                <div class="checkbox">
                    <label>
                        {!! Form::hidden('is_enabled', 0) !!}
                        {!! Form::checkbox('is_enabled') !!} Публиковать?
                    </label>
                </div>
            </div>
        </div>

    </div>
    <div role="tabpanel" class="tab-pane fade" id="seo">

        @include('backend.form_seo')

    </div>
</div>

@section('scripts')
    <script src="/vendor/midium/laravel-ckeditor/ckeditor.js"></script>
    <script>
        $(function () {
            CKEDITOR.replace('content', { customConfig: '/public/assets/backend/js/ck_content.js' });
        });
    </script>
@stop

resources/views/backend/page/confirm.blade.php
@extends('backend.layouts.default')

@section('title', 'Удалить ' . $page->title)

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Статические страницы<small><i class="fa fa-angle-right fa-fw"></i>Удалить страницу</small>
            </h1>
        </div>
    </div>

    {!! Form::open([
        'method' => 'DELETE',
        'route'  => ['backend.pages.destroy', $page->id]
    ]) !!}

    <div class="alert alert-danger">
        <p><strong>Внимание!</strong> Вы действительно хотите удалить эту страницу?</p>
        <p><i class="fa fa-file-o fa-fw"></i> {{ $page->title }}</p>
    </div>

    {!! Form::submit('Да, удалить эту страницу!', ['class' => 'btn btn-danger']) !!}

    <a href="{{ route('backend.pages.index') }}" class="btn btn-success">
        <strong>Нет, вернуться назад!</strong>
    </a>

    {!! Form::close() !!}

@stop

resources/views/backend/page/create.blade.php
@extends('backend.layouts.default')

@section('title', 'Добавить страницу')

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Статические страницы<small><i class="fa fa-angle-right fa-fw"></i>Добавить страницу</small>
            </h1>
        </div>
    </div>

    {!! Form::open([
        'route'  => 'backend.pages.store',
        'class'  => 'form-horizontal'
    ]) !!}

        @include ('backend.page._form')
        @include ('backend.form_buttons')

    {!! Form::close() !!}

@stop

resources/views/backend/page/edit.blade.php
@extends('backend.layouts.default')

@section('title', 'Редактировать страницу')

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Статические страницы<small><i class="fa fa-angle-right fa-fw"></i>Редактировать страницу</small>
            </h1>
        </div>
    </div>

    {!! Form::model($page, [
        'method' => 'PATCH',
        'route'  => ['backend.pages.update', $page->id],
        'class'  => 'form-horizontal'
    ]) !!}

        @include ('backend.page._form')
        @include ('backend.form_buttons')

    {!! Form::close() !!}

@stop

resources/views/backend/page/index.blade.php
@extends('backend.layouts.default')

@section('title', 'Управление страницами')

@section('content')

    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Статические страницы<small><i class="fa fa-angle-right fa-fw"></i>Управление страницами</small>
            </h1>
            <div class="btn-group">
                <a href="{{ route('backend.pages.create') }}" class="btn btn-success btn-sm">
                    <i class="fa fa-plus-circle fa-fw"></i> Добавить страницу
                </a>
            </div><hr>
        </div>
    </div>

    @if($pages->count())
        <table class="table table-striped table-hover">

            <thead>
            <tr>
                <th style="width: 75%; white-space: nowrap;">Заголовок страницы</th>
                <th>Статус</th>
                <th>Действия</th>
            </tr>
            </thead>

            <tbody>
            @foreach($pages as $page)
                <tr>
                    <td>
                        <a href="{{ route('backend.pages.edit', $page->id ) }}">
                            {{ $page->title }}
                        </a>
                    </td>
                    <td>
                        @if($page->is_enabled)
                            <i class="fa fa-check-circle fa-lg fa-fw text-success"></i>
                        @else
                            <i class="fa fa-check-circle fa-lg fa-fw text-danger"></i>
                        @endif
                    </td>
                    <td class="icon_actions">
                        <a href="{{ route('backend.pages.edit', $page->id ) }}" >
                            <i class="fa fa-pencil fa-lg fa-fw"></i></a>

                        <a href="{{ route('page', $page->slug) }}" target="_blank">
                            <i class="fa fa-eye fa-lg fa-fw"></i></a>

                        <a href="{{ route('backend.pages.confirm', $page->id) }}">
                            <i class="fa fa-remove fa-lg fa-fw text-danger"></i></a>
                    </td>
                </tr>
            @endforeach
            </tbody>

        </table>
    @else
        <p>Страниц нет!</p>
    @endif

@stop